### ISSUE TITLE
Erreur ApplicationSecurityTest.java has not been previously formatted

### ISSUE THREAD

**Issue by JBPressac** [tech-advantage/numahop#47]
Bonjour,

J'essaye d'installer NumaHop 2.3.0 sous Ubuntu 22.04.5 LTS en suivant le README mais la commande `mvn clean spring-boot:run -Pprod -Dspring-boot.run.profiles=prod` se termine par un message d'erreur:

```
[ERROR] Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.23.0:validate (default) on project numahop: File '/home/numahop/Applications/numahop/src/test/java/fr/progilone/pgcn/ApplicationSecurityTest.java' has not been previously formatted. Please format file (for example by invoking `mvn net.revelc.code.formatter:formatter-maven-plugin:2.23.0:format`) and commit before running validation! -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Une exécution de la même commande avec l'option -e apporte le complément d'information suivant: 

```
[ERROR] Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.23.0:validate (default) on project numahop: File '/home/numahop/Applications/numahop/src/test/java/fr/progilone/pgcn/ApplicationSecurityTest.java' has not been previously formatted. Please format file (for example by invoking `mvn net.revelc.code.formatter:formatter-maven-plugin:2.23.0:format`) and commit before running validation! -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.23.0:validate (default) on project numahop: File '/home/numahop/Applications/numahop/src/test/java/fr/progilone/pgcn/ApplicationSecurityTest.java' has not been previously formatted. Please format file (for example by invoking `mvn net.revelc.code.formatter:formatter-maven-plugin:2.23.0:format`) and commit before running validation!
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions (MojoExecutor.java:355)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:200)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:569)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoFailureException: File '/home/numahop/Applications/numahop/src/test/java/fr/progilone/pgcn/ApplicationSecurityTest.java' has not been previously formatted. Please format file (for example by invoking `mvn net.revelc.code.formatter:formatter-maven-plugin:2.23.0:format`) and commit before running validation!
```

Le contenu du fichier /src/main/resources/config/application-prod.yml est le suivant:

```
spring:
    # configuration de l'accès à la base de données
    datasource:
        url: jdbc:mariadb://numahop
        username: superuser
        password: xxx
    # configuration de l'accès à elasticsearch
    elasticsearch:
        uris:
            - http://localhost:9200
    # configuration du serveur SMTP
    mail:
        host: localhost
        port: 25
        user:
        password:
        protocol: smtp
        tls: false
        auth: false
        activated: false
        from: numahop@wsl.com

# nom de l'index elasticsearch
elasticsearch:
    index:
        name: numahop

# chemins vers imagemagick
imageMagick:
    convert: /usr/bin/convert
    identify: /usr/bin/identify

# Chemin vers exiftool
exifTool:
    process: /usr/bin/exiftool
    quot_char: ''

# Chemin vers tesseract
tesseract:
    process: /usr/bin/tesseract

# lister les bibliotheques utilisatrices comme suit: library_identifier1, library_identifier2, etc..
instance:
    libraries: crbc

# répertoires de stockage des images
storage:
    binaries: /home/numahop/Applications/NumaHopWorkBase/images

# répertoires de travail **path to workBaseDir**
uploadPath:
    condition_report: /home/numahop/Applications/NumaHopWorkBase/upload/condition_report
    ead: /home/numahop/Applications/NumaHopWorkBase/upload/ead
    import: /home/numahop/Applications/NumaHopWorkBase/upload/import
    library: /home/numahop/Applications/NumaHopWorkBase/upload/library
    user: /home/numahop/Applications/NumaHopWorkBase/upload/user
    template: /home/numahop/Applications/NumaHopWorkBase/upload/templates

# fichier de logs
logging:
    file:
        name: /home/numahop/Applications/NumaHopWorkBase/logs/numahop

# Services externes
services:
    cines:
        aip: /home/numahop/Applications/NumaHopWorkBase/cines/aip
        cache: /home/numahop/Applications/NumaHopWorkBase/cines/cache
        facile: https://facile.cines.fr/xml
        xsd:
           sip: /home/numahop/Applications/NumaHopWorkBase/xsd/sip.xsd
    archive:
        alto: /home/numahop/Applications/NumaHopWorkBase/archive/alto
        text: /home/numahop/Applications/NumaHopWorkBase/archive/text
    metaDatas:
        path: /home/numahop/Applications/NumaHopWorkBase/metadatas
    deliveryreporting:
        path: /home/numahop/Applications/NumaHopWorkBase/deliveryReporting
    omeka:
        cache: /home/numahop/Applications/NumaHopWorkBase/omeka/cache
    ftpexport:
        cache: /home/numahop/Applications/NumaHopWorkBase/ftpexport/cache
    digitalLibraryDiffusion:
        cache: /home/numahop/Applications/NumaHopWorkBase/digitalLibraryDiffusion/cache

# Clés utilisées pour le chiffrement de données chiffrées en BDD.
# Vous pouvez utiliser par exemple openssl pour générer des clés alétoires :
# openssl rand -hex 44
crypto:
    password: ***********
    salt: **********

admin:
    login: xxx
    password: xxx
```
